const CACHE_PREFIX = 'luca-guitar-interactive-';
const CACHE_VERSION = `${CACHE_PREFIX}3-0-1`;
const CORE = ['./','./index.html','./styles.css','./app.js','./mic-pro.js','./manifest.json'];
const OPTIONAL = ['./personal_catalog.json','./icon-180.png','./icon-192.png','./icon-512.png','./icon-1024.png','./ipad-pro-13-portrait.png','./ipad-pro-13-landscape.png'];
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil((async()=>{const cache=await caches.open(CACHE_VERSION);await cache.addAll(CORE);await Promise.allSettled(OPTIONAL.map(async url=>{const response=await fetch(url,{cache:'reload'});if(response.ok)await cache.put(url,response)}))})())});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX)&&key!==CACHE_VERSION).map(key=>caches.delete(key)));await self.clients.claim()})())});
async function networkFirst(request,fallbackUrl){const cache=await caches.open(CACHE_VERSION);try{const response=await fetch(request,{cache:'no-store'});if(response?.ok)await cache.put(request,response.clone());return response}catch{return(await cache.match(request))||(fallbackUrl?await cache.match(fallbackUrl):null)}}
async function staleWhileRevalidate(request){const cache=await caches.open(CACHE_VERSION),cached=await cache.match(request),update=fetch(request).then(async response=>{if(response?.ok)await cache.put(request,response.clone());return response}).catch(()=>null);return cached||await update||new Response('',{status:504,statusText:'Offline'})}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==='navigate'){event.respondWith((async()=>await networkFirst(request,'./index.html')||new Response('Offline. Bitte die App einmal vollständig online starten.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}}))());return}const isCode=/\.(?:js|css|json)$/.test(url.pathname);event.respondWith(isCode?networkFirst(request):staleWhileRevalidate(request))});
self.addEventListener('message',event=>{if(event.data==='SKIP_WAITING')self.skipWaiting()});
